version: '3'
services:
  bot:
    build: .
    image: devconnect-telegram-bot:latest
    restart: on-failure
    ports:
      - "3001:3001"
    depends_on:
      - database
      - message-bus
    volumes:
      - .:/app
    env_file:
      - .env
    command:  # install any new packages since last build then start the app
      - sh
      - -c
      - |
        npm install
        npm start

  database:
    image: mongo:7.0-jammy
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  message-bus:
    image: masstransit/rabbitmq:3
    restart: unless-stopped
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  mongo-data:
  rabbitmq-data:
  